"""Export AI agent shortlist as Ergo facts for ErgoAI integration."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any


def write_ergo_shortlist(output: dict[str, Any], path: Path) -> None:
    """Write shortlist facts loadable alongside warehouse_run.ergo."""
    lines = [
        "// ============================================================================",
        "// AI AGENT SHORTLIST - Auto-generated by LangGraph + HuggingFace pipeline",
        "// Load after warehouse_run.ergo to query AI-driven priorities",
        "// ============================================================================",
        "",
        f"// Model: {output.get('llm_model', 'unknown')}",
        f"// Pipeline: {output.get('pipeline', 'unknown')}",
        "",
    ]

    for i, agent_data in enumerate(output.get("agents", []), start=1):
        agent_name = agent_data.get("agent", f"agent_{i}")
        mode = agent_data.get("mode", "unknown")
        safe_name = re.sub(r"[^a-zA-Z0-9_]", "_", agent_name)
        lines.append(
            f"ai_agent_result({safe_name}, mode_{mode}, rank_{i})."
        )

    supervisor = output.get("supervisor", {})
    escalation = supervisor.get("escalation", False)
    lines.extend([
        "",
        f"ai_escalation_status({'yes' if escalation else 'no'}).",
        "",
        "// Query examples:",
        "//   ai_agent_result(?Agent, ?Mode, ?Rank).",
        "//   ai_escalation_status(?Status).",
        "",
    ])

    path.write_text("\n".join(lines), encoding="utf-8")
